### ISSUE TITLE
Not working - no cookie set by API when logged in

### ISSUE THREAD

**Issue by conficient** [stavroskasidis/BlazorWithIdentity#1]
I tried this yesterday on Preview 3 and it worked when I registered a user.

Upgraded to the Preview 4 version today, and it isn't working. When I log in, the request is validated by the API. I can see the cookie returned in the API call response.
![image](https://user-images.githubusercontent.com/454494/57127164-6db37200-6d87-11e9-904d-38783a97f689.png)

However, when the redirect to the root page takes place, the cookie isn't present, so the it does not appear to be logged in?
![image](https://user-images.githubusercontent.com/454494/57127185-7a37ca80-6d87-11e9-92fd-2a736867bf23.png)

**Comment by conficient** [comment]
Seems to be limited to Chrome, not sure why. I tried on Edge and Firefox and it worked. I tried Chrome in anonymous mode and it worked as well. Must be something specific to my Chrome settings, so I'll close this for now!

**Comment by stavroskasidis** [comment]
I had the EXACT same issue. This project was created to reproduce it.

Check this issue
https://github.com/aspnet/AspNetCore/issues/9894

**Comment by conficient** [comment]
It might be something Chrome has somewhere - it worked in "Guest mode" as well, so it might be account or privacy related - perhaps it needs an SSL connection? Might be worth looking at.

But thanks for the great demo app - saved me a lot of time!

**Comment by dradovic** [comment]
I had the same issue too. I believe it's related to [Chrome localhost cookie not being set](https://stackoverflow.com/questions/7346919/chrome-localhost-cookie-not-being-set) which although it is an old question seems to be a reoccurring pattern.
However, it works in Chrome in incognito mode, or when launching the site on "https". So Chrome seems to accepts the cookie from localhost over an SSL connection.
