### ISSUE TITLE
Will there be a similar implementation of authentication by Identity Server?

### ISSUE THREAD

**Issue by glazkovalex** [stavroskasidis/BlazorWithIdentity#12]
Will there be a similar implementation of authentication by Identity Server?

**Comment by enkodellc** [comment]
@glazkovalex my repo: https://github.com/enkodellc/blazorboilerplate has IS4 example and was based off of BlazorWithIdentity if you want to review mine as an example. Or if @stavroskasidis you want to use mine as a reference.
