### ISSUE TITLE
How is HttpClient authenticated. There is no access token or code passed when adding the httpclient to services DI

### ISSUE THREAD

**Issue by prince272** [stavroskasidis/BlazorWithIdentity#18]

**Comment by prince272** [comment]
I think I've found the solution. When you sign in using the httpclient the access tokens are sent and stored in the httpclient headers. 

Please let me know if I'm right. If you have a better explanations to this, please let me know.

**Comment by stavroskasidis** [comment]
It is a cookie based authentication. The auth cookie is automatically passed to the server with every request.

**Comment by prince272** [comment]
Okay! Thanks!
