### ISSUE TITLE
Using Sql Server as the Database

### ISSUE THREAD

**Issue by silentcross** [stavroskasidis/BlazorWithIdentity#23]
I try to change the sqlite to sql server, but got error 500
Step i done :
1. Adding Microsoft.EntityFrameworkCore.SqlServer
2. Change :` services.AddDbContext<ApplicationDbContext>(options => options.UseSqlite("Filename=data.db"));` to `services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(connString));`

When i register, the input username & password is inserted to database, but it say error 500
I cant login

**Comment by stavroskasidis** [comment]
I did the same and I don't see any errors, everything worked fine. What is the exact error message you get?

**Comment by silentcross** [comment]
It say Response status code does not indicate success: 500 (Internal Server Error).
