### ISSUE TITLE
Will not get user details for user already logged in

### ISSUE THREAD

**Issue by conficient** [stavroskasidis/BlazorWithIdentity#3]
An issue with this library (good as it is!) is that the `Username` is only populated if the user logs in or registers using the API. The username isn't re-populated if the user is already logged in on returning.

However his royal Blazorness Steve Sanderson says that `ClaimsPrincipal` will be made available in a later version (see https://github.com/aspnet/AspNetCore/issues/4048)

**Comment by stavroskasidis** [comment]
Well, this is just a sample, but you are right. That is a bug for the client side. Could be easily fixed with an API call to get the user name

**Comment by conficient** [comment]
Good point, I'll queue an API call if IsLoggedOn returns true..

**Comment by stavroskasidis** [comment]
I pushed an update to the sample that case
