### ISSUE TITLE
Moving Models folder from Server to Shared Project

### ISSUE THREAD

**Issue by jawaidakhter** [stavroskasidis/BlazorWithIdentity#5]
When I move models folder from server to shared project with proper references, I am not able to compile solution. Is this possible use shared project classes for Identity User and other entities.

**Comment by stavroskasidis** [comment]
I don't think you can move the Identity stuff in the shared project (nor should you) because they are part of the asp core framework, but the shared and blazor projects are .Net Standard. 

Even if you could reference them, I don't think you want info about your DB leaking to the client.
