### ISSUE TITLE
AuthorizeController.Login returns a stale UserInfo

### ISSUE THREAD

**Issue by dradovic** [stavroskasidis/BlazorWithIdentity#6]
After the call to `SignInAsync`, you return `Ok(BuildUserInfo())` which in turn uses the inhertied `User` property from the `ControllerBase` which is not updated to reflect the new user but still holds an unauthenticated user.
Luckily, `IdentityAuthenticationStateProvider.GetAuthenticationStateAsync` retrieves an updated `UserInfo` if the cached user info is unauthenticated but you end up with an extra trip to the back-end.

**Comment by enkodellc** [comment]
@dradovic do you want to submit a PR for the process that you proposed. I definitely know we need more support in the authorization / authentication areas of BlazorBoilerplate.

**Comment by dradovic** [comment]
My suggestion therefore is to not return a `UserInfo` from `AuthorizeController.Login` (and `Register`) and keep the extra round to `GetUserInfo`. That way it's sure that the return `UserInfo` is always the same (vs. constructing one in the `Login` method and returning that).

**Comment by stavroskasidis** [comment]
Thank you for the feedback. I implemented your suggestion.
