### ISSUE TITLE
PW Reset

### ISSUE THREAD

**Issue by 274188A** [stavroskasidis/BlazorWithIdentity#7]
For completeness it would nice to add a password reset feature in the demo code

**Comment by stavroskasidis** [comment]
Password reset requires pluging-in an email provider and having the user register by email. 

I want to keep the sample simple, as the point of the sample is **not** to showcase **Identity** itself. If you know how to use **Identity** you could easily extend the code to fit your needs,

**Comment by enkodellc** [comment]
@274188A My repo, https://github.com/enkodellc/blazorboilerplate, which uses BlazorWithIdentity will implement the password reset in the future. Take a look.

**Comment by enkodellc** [comment]
@274188A  I finished my initial version of the Password Reset functionality on my fork of BlazorWithIdentity:  https://github.com/enkodellc/blazorboilerplate
